site_name: Flask Training Guide
site_url: https://pragnakalpdev54.github.io/Flask/
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - content.code.copy
    - navigation.footer

nav:
  - Home: index.md

  - Course Levels:
      - Level 0 – Beginner: LEVEL_0_BEGINNER.md
      - Level 1 – Foundations: LEVEL_1_FOUNDATIONS.md
      - Level 2 – Intermediate:
          - Part A – Core Concepts: LEVEL_2A_INTERMEDIATE.md
          - Part B – Applied Flask: LEVEL_2B_INTERMEDIATE.md
      - Level 3 – Authentication & Security: LEVEL_3_AUTHENTICATION.md
      - Level 4 – Scalable Systems: LEVEL_4_SCALABLE.md
      - Level 5 – Extensions & Advanced Topics: LEVEL_5_EXTENSIONS.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - footnotes
  - codehilite

extra_css:
  - assets/stylesheets/footer.css
  
extra:
  generator: false

  copyright: |
    © 2025 Ctrl+C Ctrl+V Devs · Flask Training Guide  
    **Made by Rahul, Nikunj, Neel, Dhvanil, Mansi, Darshit**
