site_name: Flask Training Guide
site_url: https://pragnakalpdev54.github.io/Flask/
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - content.code.copy
    - navigation.footer

nav:
  - Home: index.md
  - Level 0 – Beginner: 01_LEVEL_0_BEGINNER.md
  - Level 1 – Foundations: 02_LEVEL_1_FOUNDATIONS.md
  - Test Task 1: 03_TEST_TASK_1.md
  - Level 2A – Core Concepts: 04_LEVEL_2A_INTERMEDIATE.md
  - Level 2B – Applied Flask: 05_LEVEL_2B_INTERMEDIATE.md
  - Level 3 – Authentication & Security: 06_LEVEL_3_AUTHENTICATION.md
  - Test Task 2: 07_TEST_TASK_2.md
  - Level 4 – Scalable Systems: 08_LEVEL_4_SCALABLE.md
  - Test Task 3: 10_TEST_TASK_3.md
  - Quick Reference Guide: PATTERN_CHEATSHEET.md
  - Postman Basics: POSTMAN_GUIDE_PART1_BASICS.md
  - Postman Advanced: POSTMAN_GUIDE_PART2_ADVANCED.md
  - cURL Guide: CURL_GUIDE.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - footnotes
  - codehilite

extra_css:
  - assets/stylesheets/footer.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/sidebar.css
